# -*- coding: utf-8 -*-
"""Task 17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dv679H7ZOycRzNnD1gfP7ie6IA8Bt1oU

# **Task 17**

The Assignment: You are a Quantitative Analyst. Your boss wants to know which sector has performed better this year on a risk-adjusted basis: Big Tech or Big Banks.

Task: Write a prompt for your Local smolagents (Qwen 3B) agent to perform the following steps autonomously:

Data Ingestion: Download daily closing prices for the last 180 days for a Tech Portfolio (NVDA, AAPL, MSFT) and a Bank Portfolio (JPM, BAC, C).

**Financial Math:**

1. Calculate the Daily Returns for each stock.
2. Calculate the Sharpe Ratio for each stock (Assume risk-free rate = 0, so simply Mean Daily Return / Std Dev of Daily Returns * sqrt(252)).

**Visualization:**

Create a Bar Chart comparing the Sharpe Ratios of all 6 companies.

Color code the bars: Green for Tech, Blue for Banks.

Output: Save the chart as sharpe_comparison.png.
"""

# ==========================================
# Install Dependencies
# ==========================================
# We need 'accelerate' and 'bitsandbytes' to load the model efficiently on the GPU.
# Added 'duckduckgo_search' to enable web search capabilities for the agent.
!pip install -q smolagents transformers accelerate bitsandbytes yfinance seaborn matplotlib duckduckgo_search

# ==========================================
# Load the 3B Model (Lightweight & Fast)
# ==========================================
from smolagents import CodeAgent, TransformersModel
import torch

print("⬇️ Downloading Qwen 2.5 Coder 3B (approx 6GB)...")

# We use the 3B-Instruct model.
# device_map="auto" finds the Colab GPU.
# torch_dtype=torch.float16 cuts memory usage in half.
model = TransformersModel(
    model_id="Qwen/Qwen2.5-Coder-3B-Instruct",
    device_map="auto",
    torch_dtype=torch.float16,
    max_new_tokens=2048  # Give it space to write longer scripts
)

print("✅ 3B Model loaded on GPU! Ready for coding.")

# ==========================================
# Initialize the Agent
# ==========================================

# We authorize the agent to use specific data science libraries, and now also a web search library.
agent = CodeAgent(
    tools=[], # We don't need pre-made tools; the agent writes its own code.
    model=model,
    max_steps=3,
    additional_authorized_imports=[
        "yfinance",
        "pandas",
        "numpy",
        "seaborn",
        "matplotlib.pyplot",
        "duckduckgo_search" # Added for web search capabilities
    ]
)

# ==========================================
# Execute the Crypto Heatmap Task
# ==========================================
# We give it a complex multi-step instruction.
task_prompt = """
1. Download daily closing data for 'NVDA', 'AAPL', 'MSFT', 'JPM', 'BAC' and 'C' for the last 180 days using yfinance.
2. Create a single DataFrame with these close prices.
3. Calculate the daily returns according to these close prices.
4. Calculate the Sharpe Ratio for each stock (Assume risk-free rate = 0, so simply Mean Daily Return / Std Dev of Daily Returns * sqrt(252))
5. Create a Bar Chart comparing the Sharpe Ratios of all 6 companies.
6. Color code the bars: Green for 'NVDA' ,'AAPL' and 'MSFT', Blue for 'JPM', 'BAC' and 'C'.
7. Save the chart as 'sharpe_comparison.png'
"""

print("🤖 Agent is coding... (Watch the 'Thought' process below)")
result = agent.run(task_prompt,stream=False)

print(result)

# ==========================================
# Display the Result
# ==========================================
import IPython
import os

if os.path.exists("sharpe_comparison.png"):
    print("\n📊 Displaying Generated Sharpe:")
    IPython.display.display(IPython.display.Image("sharpe_comparison.png"))
else:
    print("⚠️ No image file found. Check the agent's output logs above for errors.")

